repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
  - id: go-imports
  - id: golangci-lint
  - id: go-unit-tests
