openapi: '3.0.2'
info:
  title: BitMe URL shortener
  version: '1.0'
servers:
  - url: https://api.server.test/v1
components:
  schemas:
    URLs:
      type: object
      properties:
        fullURL:
          type: string
        shortURL:
          type: string
    Data:
      type: object
      properties:
        NumOfRedirects:
          type: integer
          format: int64
        #some other data in future maybe
paths:
  /shortenURL:
    post:
      operationId: SendFullURL
      parameters:
        - name: fullURL
          in: query
          description: fullURL to shorten
          required: false #mb needs to be true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLs"
        '400':
          description: not a URL
    get:
      operationId: GetShortURL
      parameters:
        - name: shortURL
          in: header
          description: shortURL to be passed as header
          required: false #mb needs to be true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLs"
        '500':
          description: couldn't generate short URL
  /getData:
    post:
      operationId: SendShortURL
      parameters:
        - name: shortURL
          in: query
          description: shortURL to find data
          required: false #mb needs to be true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLs"
        '404':
          description: short URL not found
    get:
      operationId: GetData
      parameters:
        - name: data
          in: header
          description: data to be passed as header
          required: false #mb needs to be true
          schema:
            $ref: "#/components/schemas/Data"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Data"
        '404':
          description: data not found
