// Package openapichi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package openapichi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// URLs defines model for URLs.
type URLs struct {
	Data     *string `json:"data,omitempty"`
	FullURL  *string `json:"fullURL,omitempty"`
	ShortURL *string `json:"shortURL,omitempty"`
}

// GetDataJSONBody defines parameters for GetData.
type GetDataJSONBody URLs

// GetUserURLsJSONBody defines parameters for GetUserURLs.
type GetUserURLsJSONBody URLs

// GenShortURLJSONBody defines parameters for GenShortURL.
type GenShortURLJSONBody URLs

// GetDataJSONRequestBody defines body for GetData for application/json ContentType.
type GetDataJSONRequestBody GetDataJSONBody

// GetUserURLsJSONRequestBody defines body for GetUserURLs for application/json ContentType.
type GetUserURLsJSONRequestBody GetUserURLsJSONBody

// GenShortURLJSONRequestBody defines body for GenShortURL for application/json ContentType.
type GenShortURLJSONRequestBody GenShortURLJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /getData)
	GetData(w http.ResponseWriter, r *http.Request)

	// (GET /home)
	GetUserURLs(w http.ResponseWriter, r *http.Request)

	// (POST /shortenURL)
	GenShortURL(w http.ResponseWriter, r *http.Request)

	// (GET /su/{shortURL})
	Redirect(w http.ResponseWriter, r *http.Request, shortURL string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetData operation middleware
func (siw *ServerInterfaceWrapper) GetData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetData(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetUserURLs operation middleware
func (siw *ServerInterfaceWrapper) GetUserURLs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserURLs(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GenShortURL operation middleware
func (siw *ServerInterfaceWrapper) GenShortURL(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenShortURL(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Redirect operation middleware
func (siw *ServerInterfaceWrapper) Redirect(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "shortURL" -------------
	var shortURL string

	err = runtime.BindStyledParameter("simple", false, "shortURL", chi.URLParam(r, "shortURL"), &shortURL)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortURL", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Redirect(w, r, shortURL)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/getData", wrapper.GetData)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/home", wrapper.GetUserURLs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shortenURL", wrapper.GenShortURL)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/su/{shortURL}", wrapper.Redirect)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xVTW/bMAz9KwK3oxGlXXfxsdgHBmSXFDkNPag2naiwJY2kAxSB//tAOW7WzgGGDRt6",
	"6MkOST0+vRfSB6hil2LAIAzlAbjaYefy62a9ys9EMSGJx/yrduL0KQ8JoQQW8mELQwFN37ab9Wo2x7tI",
	"Mp8ciikS7+6xEhg05EMTc7GXVnPXXr6i2axXJkNhQIIC9kjsY4ASLhZL7RMTBpc8lPBusVxcQgHJyS7z",
	"tluUD0fuKbLkuyBX5JOMGJ9RjN7ONJEMRxLtBxmUnNZ8qceqDFMA4fceWa5j/aBgVQyCIeO6lFpf5TP2",
	"nhV8Elbf3hI2UMIbe1LeHmW3WfOswFNuimLutNPY1xPWUAr1OGiAUww8+nO5XP5zNtxXFTI3fWsexVH5",
	"r5ZXv8qaDcvWhSimiX2otfb9yPNprQ+CFFxrGGmPZJAokjIYCrC72KEe2eIZ85SuaSh2ZnPzcT3n3IaR",
	"8qVeuHu/K/dMsYrs8j/3j0Q+jtdxVs8NSlAWaB6tndE63Ewz/zop/8m63h6mRTucHZQ11p6wEiPRfDqu",
	"7OfuTTV5f5LrUJAYym8H8AqhOxUKCK7Dab5PPp/0Ln7S7vnSv33pW+tv95V+9HJs1K2nFkrYiSQurXXJ",
	"L8bsQpDF7i9guB1+BAAA//8qKgvCiwcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
