// Package apichi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package apichi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// URLs defines model for URLs.
type URLs struct {
	Data     *string `json:"data,omitempty"`
	FullURL  *string `json:"fullURL,omitempty"`
	ShortURL *string `json:"shortURL,omitempty"`
}

// GetDataParams defines parameters for GetData.
type GetDataParams struct {
	// data to be passed as header
	Data *URLs `json:"data,omitempty"`
}

// SendShortURLParams defines parameters for SendShortURL.
type SendShortURLParams struct {
	// shortURL to find data
	ShortURL *string `json:"shortURL,omitempty"`
}

// GetShortURLParams defines parameters for GetShortURL.
type GetShortURLParams struct {
	// shortURL to be passed as header
	ShortURL string `json:"shortURL"`
}

// SendFullURLParams defines parameters for SendFullURL.
type SendFullURLParams struct {
	// fullURL to shorten
	FullURL string `json:"fullURL"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /getData)
	GetData(w http.ResponseWriter, r *http.Request, params GetDataParams)

	// (POST /getData)
	SendShortURL(w http.ResponseWriter, r *http.Request, params SendShortURLParams)

	// (GET /shortenURL)
	GetShortURL(w http.ResponseWriter, r *http.Request, params GetShortURLParams)

	// (POST /shortenURL)
	SendFullURL(w http.ResponseWriter, r *http.Request, params SendFullURLParams)

	// (GET /{shortURL})
	Redirect(w http.ResponseWriter, r *http.Request, shortURL string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetData operation middleware
func (siw *ServerInterfaceWrapper) GetData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDataParams

	headers := r.Header

	// ------------- Optional header parameter "data" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("data")]; found {
		var Data URLs
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "data", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "data", runtime.ParamLocationHeader, valueList[0], &Data)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "data", Err: err})
			return
		}

		params.Data = &Data

	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetData(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// SendShortURL operation middleware
func (siw *ServerInterfaceWrapper) SendShortURL(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SendShortURLParams

	// ------------- Optional query parameter "shortURL" -------------
	if paramValue := r.URL.Query().Get("shortURL"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "shortURL", r.URL.Query(), &params.ShortURL)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortURL", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendShortURL(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetShortURL operation middleware
func (siw *ServerInterfaceWrapper) GetShortURL(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetShortURLParams

	headers := r.Header

	// ------------- Required header parameter "shortURL" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("shortURL")]; found {
		var ShortURL string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "shortURL", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "shortURL", runtime.ParamLocationHeader, valueList[0], &ShortURL)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortURL", Err: err})
			return
		}

		params.ShortURL = ShortURL

	} else {
		err := fmt.Errorf("Header parameter shortURL is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "shortURL", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShortURL(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// SendFullURL operation middleware
func (siw *ServerInterfaceWrapper) SendFullURL(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SendFullURLParams

	// ------------- Required query parameter "fullURL" -------------
	if paramValue := r.URL.Query().Get("fullURL"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "fullURL"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "fullURL", r.URL.Query(), &params.FullURL)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fullURL", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendFullURL(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Redirect operation middleware
func (siw *ServerInterfaceWrapper) Redirect(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "shortURL" -------------
	var shortURL string

	err = runtime.BindStyledParameter("simple", false, "shortURL", chi.URLParam(r, "shortURL"), &shortURL)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortURL", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Redirect(w, r, shortURL)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/getData", wrapper.GetData)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/getData", wrapper.SendShortURL)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shortenURL", wrapper.GetShortURL)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shortenURL", wrapper.SendFullURL)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{shortURL}", wrapper.Redirect)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9yUzW7bMAzHX0XgBuxixGnXXXwchg0DskuKnIYeVItOVDiSKtIBisDvPlCW89EmSLee",
	"upNsk+LHj39zC7VfB+/QMUG1BapXuNbpcTGfpTNEHzCyxfRmNGs5+SkgVEAcrVtCX0DTte1iPjtpo5WP",
	"fNrYF+MXf/+ANUMvn6xrfHK23Irtq+VfqBbzmUqh0GGEAjYYyXoHFVxNppLHB3Q6WKjg82Q6uYYCguZV",
	"qrtcIn/LtS+R5ZC2NFvvfhqo4Ee2y52o18gYCarfWzBIdbSBh0zSv2Kv7lEFTYRGaVIr1CZVZMVl9+b0",
	"GvMVKDJaSfwxYgMVfCj37MsMvkzU+/6ugIgUvKMB+/V0KkftHaNL1esQWlun+ssHktq2BymeU+6LZ31Q",
	"V9dI1HSt2nEQhDfTmzTml007z6rxnTNDuODpBMVbdOZ2nPYFlKMqBGdjnVEZVIL42GF82jOkfczzTb4V",
	"2ivm8jaOqYsk4yOYfQFl1nX+Sc4p9F/Q/oVSDyhHfOxsRAMVxw7fC/UvQ+5j59p3rXGfWC1lb2hGtZvD",
	"JSl/z0vtAu68+4R2nuMZGTe7eO+T780pvqJlPdIULW9HHfUHWj6+M0djI9YsyPaQjwcw+rykn9DKav+P",
	"pPvKxSsBCeNmRNHFVn5k5kBVWepgJ4N1wkhcbq6gv+v/BAAA//9ksc1d5QcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
