openapi: '3.0.2'
info:
  title: BitMe URL shortener
  version: '1.0'
servers:
  - url: https://api.server.test/v1
components:
  schemas:
    URLs:
      type: object
      properties:
        fullURL:
          type: string
        shortURL:
          type: string
        data:
          type: string
      #some other data in future maybe
paths:
  /shortenURL:
    post:
      operationId: SendFullURL
      parameters:
        - name: fullURL
          in: query
          description: fullURL to shorten
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLs"
        '400':
          description: not a URL
  /getData:
    post:
      operationId: SendShortURL
      parameters:
        - name: shortURL
          in: query
          description: shortURL to find data
          required: false #mb needs to be true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLs"
        '404':
          description: short URL not found
  /{shortURL}:
    get:
      description: Redirect to FullURL
      operationId: Redirect
      parameters:
        - name: shortURL
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
           description: successful operation
           content:
            application/json:
                schema:
                  $ref: "#/components/schemas/URLs"
        '404':
          description: data not found
